import v from"./supercomponent.js";import{html as r,render as c}from"./lit-html.js";import{unsafeHTML as d}from"./unsafe-html.js";import a from"./env.js";import{parseDataset as p}from"./general.js";import{UUID as f}from"./uuid.js";class u extends v{constructor(e){super();this.handleClick=e=>{const i=e.currentTarget.getBoundingClientRect(),n=new m(this.model.uid,this.model.items);document.body.appendChild(n);const o=n.getBoundingClientRect();let s=i.top+i.height;s+o.height>=window.innerHeight&&(s=i.top-o.height);let l=i.left;l+o.width>=window.innerWidth&&(l=i.left+i.width-o.width),n.style.top=`${s}px`,n.style.left=`${l}px`,n.classList.toggle("is-visible")};this.model={icon:'<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" /></svg>',items:[],tooltip:null,class:"",css:"",attributes:{},uid:f()},this.model=p(this.dataset,this.model),a.css("overflow-menu").then(()=>{this.set(e,!0),this.render()})}connected(){document.addEventListener("click",()=>{document.body.querySelectorAll(`overflow-menu-container[overflow-menu-container-id="${this.model.uid}"].is-visible`).forEach(e=>{e.remove()})},{passive:!0,capture:!0}),window.addEventListener("resize",()=>{document.body.querySelectorAll(`overflow-container[overflow-menu-container-id="${this.model.uid}"].is-visible`).forEach(e=>{e.remove()})},{passive:!0,capture:!0}),window.addEventListener("scroll",()=>{document.body.querySelectorAll(`overflow-container[overflow-menu-container-id="${this.model.uid}"].is-visible`).forEach(e=>{e.remove()})},{passive:!0,capture:!0}),this.addEventListener("click",e=>{e.stopImmediatePropagation()})}render(){this.style.cssText=this.model.css,this.className=this.model.class,Object.keys(this.model.attributes).map(t=>{this.setAttribute(t,`${this.model.attributes[t]}`)});const e=r`
            <button @click=${this.handleClick} sfx="button" type="button" aria-label="${this.model.tooltip||"open menu"}" tooltip>${d(this.model.icon)}</button>
        `;c(e,this)}}a.mount("overflow-menu",u);class m extends HTMLElement{constructor(e,t){super();this.handleItemClick=e=>{const t=e.currentTarget,i=parseInt(t.dataset.index);this.items?.[i]?.callback()};this.uid=e,this.items=t,this.render()}renderItem(e,t){return e===null?r`<hr />`:r`
            <button sfx="button" type="button" @click=${this.handleItemClick} data-index="${t}" class="${e?.danger?"danger":""}">
                ${e?.icon?r` <i> ${d(e.icon)} </i> `:""}
                <span>${e.label}</span>
            </button>
        `}render(){this.setAttribute("overflow-menu-container-id",this.uid);const e=r`
            ${this.items.map((t,i)=>this.renderItem(t,i))}
        `;c(e,this)}}a.mount("overflow-menu-container",m);export{u as default};
