import{html as i,render as c}from"./lit-html.js";import d from"./supercomponent.js";import o from"./env.js";import{noop as n,parseDataset as u}from"./general.js";import{unsafeHTML as p}from"./unsafe-html.js";import v from"./sortablejs.js";import"./button.js";import{UUID as g}from"./uuid.js";class h extends d{constructor(t){super(),this.model={tabs:[],callback:n,active:0,css:"",class:"",attributes:{},sortable:!1,sortCallback:n,addCallback:n,removeCallback:n,expandable:!1,shrinkable:!1},this.model=u(this.dataset,this.model),o.css(["tabs","button"]).then(()=>{this.set(t,!0),this.render()})}getOrder(){const t=[];return this.querySelectorAll("tab-component").forEach(e=>{t.push(e.model.value)}),t}callback(t,e){this.set({active:e},!0),this.model.callback(t),this.querySelectorAll("tab-component").forEach(s=>{s.index===e?s.classList.add("is-active"):s.classList.remove("is-active")})}sort(){const t=this.querySelector("tabs-container");v.create(t,{onUpdate:e=>{const s=this.getOrder();this.model.sortCallback(s)}})}addTab(){const t=window.prompt("New Tab Label");if(t!=null&&t.trim()!==""){const e=g();this.model.addCallback(t.trim(),e);const s={label:t,value:e},a=this.get();a.tabs.push(s),this.set(a,!0);const r=new l(s,this,!0,a.tabs.length-1,this.model.shrinkable);this.querySelector("tabs-container").appendChild(r),this.sort(),this.callback(e,a.tabs.length-1),this.resetIndexes()}}resetIndexes(){this.querySelectorAll("tab-component").forEach((t,e)=>{t.index=e})}renderAddButton(){let t;return this.model.expandable?t=i`
                <button-component
                    data-kind="text"
                    data-color="grey"
                    data-icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>'
                    data-icon-position="center"
                    data-shape="round"
                    style="margin-bottom:6px;"
                    @click=${this.addTab.bind(this)}
                ></button-component>
            `:t="",t}render(){this.className=this.model.class,this.style.cssText=this.model.css,Object.keys(this.model.attributes).map(e=>{this.setAttribute(e,`${this.model.attributes[e]}`)});const t=i`
            <tabs-container>
                ${this.model.tabs.map((e,s)=>{const a=s===this.model.active;return i`${new l(e,this,a,s,this.model.shrinkable)}`})}
            </tabs-container>
            ${this.renderAddButton()}
        `;c(t,this),this.model.sortable&&setTimeout(this.sort.bind(this),80)}}class l extends d{constructor(e,s,a,r,b){super();this.handleClick=e=>{this.parent.callback(this.model.value,this.index)};this.model=e,this.isActive=a,this.parent=s,this.index=r,this.shrinkable=b,this.render()}renderIcon(){let e;return this.model?.icon instanceof HTMLElement?e=i`<i>${this.model.icon}</i>`:typeof this.model?.icon=="string"&&this.model?.icon?.length?e=i` <i> ${p(this.model.icon)} </i> `:e="",e}render(){const e=i`<span>${this.renderIcon()} ${this.model.label}</span>`;this.tabIndex=0,this.setAttribute("sfx","button"),this.className=`${this.isActive?"is-active":""} ${this.model?.icon?"has-icon":""}`,this.setAttribute("role","button"),this.setAttribute("aria-label",`Open ${this.model.label}`),c(e,this)}connected(){this.addEventListener("click",this.handleClick)}disconnected(){this.removeEventListener("click",this.handleClick)}}o.bind("tab-component",l),o.bind("tabs-component",h);export{h as default};
