name: Deployment

on:
    push:
        branches:
            - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node and NPM
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.5

    - name: Install NPM Packages
      run: npm ci

    - name: Compile
      run: npm run production

    - name: Load SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSHKEY }}

    - name: Deploy
      run: rsync -azh --delete-after -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/brixi-ui/

    - name: Post Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: /home/${{ secrets.USERNAME }}/.nvm/versions/node/v14.18.1/bin/pm2 restart 0
        
    # - name: Purge cache
    #   uses: nathanvaughn/actions-cloudflare-purge@master
    #   if: success()
    #   with:
    #     cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
    #     cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}