name: Deployment

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node and NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 16.13.2

            - name: Install NPM Packages
              run: npm ci

            - name: Verify
              run: npm run lint:tsc

            - name: Deploy
              run: npm run deploy

            - name: Purge cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              if: success()
              with:
                  cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
                  cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
